xpens/xpens/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.conf import settings

from app.views import (
    LoginView,
    HomeView,
    OverviewView,
)
from user_mgmt.views import (
    RegistrationView,
    PasswordChangeView,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^login/$', LoginView.as_view(),
        {
            "template_name": "app/login.html",
            "extra_context": {"next": reverse_lazy('home')},
        },
        name="login"),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            "next_page": reverse_lazy('login'),
        },
        name="logout"),
    url(r'^password/change/$',
        PasswordChangeView.as_view(),
        name="password_change"),
    url(r'^overview/$', OverviewView.as_view(),
        name="overview"),
    url(r'^expenses/', include('app.expenses_urls')),
    url(r'^categories/', include('app.categories_urls')),
    url(r'^statistics/', include('app.statistics_urls')),
    url(r'^captcha/', include('captcha.urls')),
]

if settings.REGISTRATION_ENABLED:
    urlpatterns += [
        url(r'^register/$',
            RegistrationView.as_view(),
            name="register"),
    ]

xpens/app/forms.py
from django import forms
from django.forms import ModelForm

from .models import (
    Expense,
    Category,
)


class NewExpenseForm(ModelForm):
    date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                           input_formats=('%d/%m/%Y',))

    class Meta:
        model = Expense
        fields = ['date', 'amount', 'description', 'category']
        widgets = {
            'amount': forms.TextInput(),
        }


class NewCategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ['name', 'description']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(NewCategoryForm, self).__init__(*args, **kwargs)
        self.instance.user = user

    def clean_name(self):
        name = self.cleaned_data['name']
        duplicates = Category.objects.by_user(self.instance.user).by_name(name)
        if self.instance.pk:
            duplicates = duplicates.exclude(pk=self.instance.pk)
        if duplicates:
            raise forms.ValidationError("Category already exists")
        return name

xpens/templates/app/expenses/delete_confirm.html
{% extends "base.html" %}

{% block page_title %}
Xpens - Confirm Expense Deletion
{% endblock %}

{% block content %}
{% include "app/nav.html" %}
<div class="row">
  <div class="col-md-6">
    <form role="form" action="." method="post">
      {% csrf_token %}
      <p>
        Do you want to the delete the expense?
      </p>
      <div>
        <input type="submit" class="btn btn-danger" value="Delete" />
        <a href="{% url 'list_expenses' %}" class="btn btn-default">Cancel</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#expenses').addClass('active');
  });
</script>
{% endblock custom_js %}

xpens/templates/app/expenses/list.html
{% extends "base.html" %}

{% block page_title %}
Xpens - Expenses
{% endblock %}

{% block custom_css %}
<style type="text/css">
  td, th {
  padding: 10px;
  }
  table {
  font-size: 12px;
  }
</style>
{% endblock %}

{% block content %}
<div class="row">
  {% include "app/nav.html" %}
  <div class="col-md-8">
    <div class="row">
      {% include "app/messages.html" %}
      <div class="col-md-3">
        <select class="form-control">
          <option value="">Select a category</option>
          <option value="{% url 'list_expenses' %}">All categories</option>
          {% for category in category_list %}
          <option value="{% url 'list_expenses_category' category_id=category.id%}" {% if category_name == category.name %}selected{% endif %}>{{ category.name }}</option>
          {% endfor %}
        </select>
        <br/>
      </div>
      <div class="col-md-3">
        <select class="form-control">
          <option value="">Select a period</option>
          {% if category_id %}
          {% with "list_expenses_category_date_range" as my_url %}
          <option value="{% url 'list_expenses_category' category_id=category_id %}">All</option>
          <option value="{% url my_url category_id=category_id from_date=cm_f_date to_date=today %}">Current month</option>
          <option value="{% url my_url category_id=category_id from_date=pm_f_date to_date=pm_t_date %}">Previous month</option>
          <option value="{% url my_url category_id=category_id from_date=cpm_f_date to_date=cpm_t_date %}">Current & previous month</option>
          <option value="{% url my_url category_id=category_id from_date=six_f_date to_date=six_t_date %}">Current & last 6 months</option>
          <option value="{% url my_url category_id=category_id from_date=cy_f_date to_date=cy_t_date %}">Current year</option>
          <option value="{% url my_url category_id=category_id from_date=py_f_date to_date=py_t_date %}">Previous year</option>
          {% endwith %}
          {% else %}
          {% with "list_expenses_date_range" as my_url %}
          <option value="{% url 'list_expenses' %}">All</option>
          <option value="{% url my_url from_date=cm_f_date to_date=today %}">Current month</option>
          <option value="{% url my_url from_date=pm_f_date to_date=pm_t_date %}">Previous month</option>
          <option value="{% url my_url from_date=cpm_f_date to_date=cpm_t_date %}">Current & previous month</option>
          <option value="{% url my_url from_date=six_f_date to_date=six_t_date %}">Current & last 6 months</option>
          <option value="{% url my_url from_date=cy_f_date to_date=cy_t_date %}">Current year</option>
          <option value="{% url my_url from_date=py_f_date to_date=py_t_date %}">Previous year</option>
          {% endwith %}

          {% endif %}

        </select>
        <br/>
      </div>
      <div style="float:right">
        <form class="navbar-form" role="search" action="{% url 'search_expenses' %}">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q" id="search-term">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            All Expenses {% if category_wise %} in {{ category_name }}{% endif %} {% if date_range %} from {{ from_date }} to {{ to_date }} {% endif %}
            <span style="float:right;"><a href="{% url 'new_expense' %}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> New Expense</a></span>
          </div>
          <div class="panel-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th class="col-md-6">Description</th>
                  <th>Category</th>
                  <th>Amount</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for expense in expenses %}
                <tr>
                  <td>{{ expense.date }}</td>
                  <td>{{ expense.description }}</td>
                  <td>{{ expense.category }}</td>
                  <td>{{ expense.amount }}</td>
                  <td>
                    <i class="fa fa-edit"></i> <a href="{% url 'update_expense' expense.id %}">Edit</a>&nbsp;
                    <i class="fa fa-trash"></i> <a href="{% url 'delete_expense' expense.id %}">Delete</a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="5">
                    <span style="text-align:center;">No expenses saved</span>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% if is_paginated %}
            <ul class="pager">
              <li class="previous{% if not page_obj.has_previous %} disabled{% endif %}">
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" class="previous">Previous</a>
              </li>
              <li class="next{% if not page_obj.has_next %} disabled{% endif %}">
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" class="next">Next</a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#expenses').addClass('active');
    $(".alert").alert();
    $("select").change(function(){
      var url = $(this).val();
      if (url) {
        window.location = url;
      }
      return false;
    });
    $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
      $(".alert-success").alert('close');
    });
  });
</script>
{% endblock %}

xpens/templates/app/expenses/new.html
{% extends "base.html" %}

{% load staticfiles %}

{% block page_title %}
Xpens - New Expense
{% endblock %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" />
{% endblock %}

{% block content %}

{% include "app/nav.html" %}

{% with form_title="New Expense" back_url_name="list_expenses" %}
{% include "app/form.html" %}
{% endwith %}

{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('input[type=text]').addClass('form-control');
    $('input[type=password]').addClass('form-control');
    $('select').addClass('form-control');
    $('label').addClass('col-md-2 control-label');
    $('textarea').addClass('form-control');
    $('#expenses').addClass('active');
    $('#id_date').attr('data-date-format','DD/MM/YYYY');
    $('#id_date').datetimepicker({
      pickTime: false
    });
  });
</script>
{% endblock custom_js %}

xpens/templates/app/expenses/search.html
{% extends "base.html" %}

{% block page_title %}
Xpens - Search Expenses
{% endblock %}

{% block custom_css %}
<style type="text/css">
  td, th {
  padding: 10px;
  }
  table {
  font-size: 12px;
  }
</style>
{% endblock %}

{% block content %}
<div class="row">
  {% include "app/nav.html" %}
  <div class="col-md-8">
    <div class="row">
      {% include "app/messages.html" %}
      <div style="float:right">
        <form class="navbar-form" role="search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q" id="search-term" value="{{ search_value }}">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Search results
            <span style="float:right;"><a href="{% url 'new_expense' %}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> New Expense</a></span>
          </div>
          <div class="panel-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th class="col-md-6">Description</th>
                  <th>Category</th>
                  <th>Amount</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for expense in expenses %}
                <tr>
                  <td>{{ expense.date }}</td>
                  <td>{{ expense.description }}</td>
                  <td>{{ expense.category }}</td>
                  <td>{{ expense.amount }}</td>
                  <td>
                    <i class="fa fa-edit"></i> <a href="{% url 'update_expense' expense.id %}">Edit</a>&nbsp;
                    <i class="fa fa-trash"></i> <a href="{% url 'delete_expense' expense.id %}">Delete</a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="5">
                    <span style="text-align:center;">No matching expenses</span>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% if is_paginated %}
            <ul class="pager">
              <li class="previous{% if not page_obj.has_previous %} disabled{% endif %}">
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" class="previous">Previous</a>
              </li>
              <li class="next{% if not page_obj.has_next %} disabled{% endif %}">
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" class="next">Next</a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
        <a href="{% url 'list_expenses' %}" style="float:right;">&lt; Back to All Expenses</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#expenses').addClass('active');
    $(".alert").alert();
    $("select").change(function(){
      var url = $(this).val();
      if (url) {
        window.location = url;
      }
      return false;
    });
    $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
      $(".alert-success").alert('close');
    });
  });
</script>
{% endblock %}

xpens/templates/app/expenses/update.html
{% extends "base.html" %}

{% load staticfiles %}

{% block page_title %}
Xpens - Update Expense
{% endblock %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" />
{% endblock %}


{% block content %}
{% include "app/nav.html" %}
{% with form_title="Update Expense"  back_url_name="list_expenses" %}
{% include "app/form.html" %}
{% endwith %}
{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('input[type=text]').addClass('form-control');
    $('input[type=password]').addClass('form-control');
    $('label').addClass('col-md-2 control-label');
    $('textarea').addClass('form-control');
    $('select').addClass('form-control');
    $('#expenses').addClass('active');
    $('#id_date').attr('data-date-format','DD/MM/YYYY');
    $('#id_date').datetimepicker({
      pickTime: false
    });
  });
</script>
{% endblock %}